version: '3'
services:            #services => separate services or essentially types of containers 
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build: .
    ports:
     - "4001:8081"   #The firsr number is the port on your local machine,The second is th port inside the container